behaviors:
  SoccerTwos:
    trainer_type: mpo
    hyperparameters:
      dual_constraint: 0.1
      kl_constraint: 0.01 # constraint for discrete case (M-step)
      alpha_max: 1.0
      alpha_scale: 10.0 # scaling factor for lagrangian multiplier (M-step)
      batch_size: 256 # minibatch size
      mstep_iteration_num: 1 # Number of iterations for M-Step
      evaluate_episode_maxstep: 200 # Maximum evaluate steps of an episode
      buffer_size: 200000
      critic_learning_rate: 0.001
      actor_learning_rate: 0.001
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple # maybe change (default: simple)
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000 # 50M
    time_horizon: 128
    summary_freq: 2000
    self_play:
      save_steps: 50000
      # team_change: 200000
      # swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
