behaviors:
  GoalieBrain:
    trainer_type: mpo
    hyperparameters:
      batch_size: 128
      buffer_size: 2000
      learning_rate: 0.001
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple # maybe change (default: simple)
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0 # maybe change (default: 1.0)
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 128
    summary_freq: 2000
    self_play:
      save_steps: 50000
      # team_change: 200000
      # swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

  StrikerBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2000
      learning_rate: 0.001
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple # maybe change (default: simple)
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0 # maybe change (default: 1.0)
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 128
    summary_freq: 2000
    self_play:
      save_steps: 50000
      # team_change: 200000
      # swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

# To set the max and min reward of -1 and 1
# environment_parameters:
#   scale:
#     sampler_type: uniform
#     sampler_parameters:
#       min_value: -1.0
#       max_value: 1.0


