behaviors:
  SoccerTwos:
    trainer_type: dqn
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 64
      buffer_size: 50000
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      exploration_schedule: linear
      exploration_initial_eps: 0.8
      exploration_final_eps: 0.05
    network_settings:
      normalize: false
      hidden_units: 20
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 10
    summary_freq: 1000
    self_play:
      save_steps: 50000
      # team_change: 200000
      # swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
